### ISSUE TITLE
Template to be optional

### ISSUE THREAD

**Issue by alaabadran** [collinforrester/grunt-explainjs#4]
Thank you for your awesome work.
Could you please add an option for HTML template. This way, i can use my own template for documents.
I see the static path for current template ('node_modules/grunt-explainjs/tasks/templates/_out.hbs')
that could be read from options of the option was passed.

**Comment by collinforrester** [comment]
I will look at it when I get a chance (probably this weekend),  otherwise I'd be more than happy to accept a PR :)

**Comment by alaabadran** [comment]
Added. And pull request was sent.
